task: waymo
source_path: ./data/waymo/121
exp_name: waymo_val_121
resume: True

data:
    split_train: -1
    split_test: 2
    type: Waymo
    white_background: false
    selected_frames: [98, 198]
    cameras: [0]
    extent: 20.
    use_colmap: true

model:
    gaussian:
        sh_degree: 1
        fourier_dim: 1
        fourier_scale: 1.
        flip_prob: 0.2
    nsg:
        include_bkgd: true
        include_obj: true
        include_sky: true
        opt_track: true

train:
    iterations: 30000
    test_iterations: [7000, 30000]
    checkpoint_iterations: [7000, 30000]

optim:
    prune_box_interval: 100
    densification_interval: 100
    densify_from_iter: 500
    densify_grad_threshold_bkgd: 0.0006
    densify_grad_abs_bkgd: True
    densify_grad_threshold_obj: 0.0006
    densify_grad_abs_obj: True
    feature_lr: 0.0025
    min_opacity: 0.005
    opacity_lr: 0.05
    opacity_reset_interval: 3000
    percent_big_ws: 0.1
    percent_dense: 0.01
    position_lr_delay_mult: 0.01
    position_lr_final: 1.6e-06
    position_lr_init: 0.00016
    position_lr_init_obj: 1.6e-05
    position_lr_max_steps: 30000
    rotation_lr: 0.001
    scaling_lr: 0.005
    semantic_lr: 0.01

    lambda_dssim: 0.2
    lambda_mask: 0.1
    lambda_reg: 0.1
    lambda_sky: 0.05
    lambda_depth_lidar: 0.01
    lambda_lpips: 0.5
    lambda_novel: 0.1

    track_position_lr_delay_mult: 0.2
    track_position_lr_init: 0.0005
    track_position_lr_final: 0.0001
    track_position_max_steps: 30000

    track_rotation_lr_delay_mult: 0.5
    track_rotation_lr_init: 0.00001
    track_rotation_lr_final: 0.000005
    track_rotation_max_steps: 30000

diffusion:
    use_diffusion: True
    config_path: video_diffusion/configs/inference/waymo_high_res.yaml
    ckpt_path: video_diffusion/ckpts/vista_condition_high_res_mix_v2.safetensors
    height: 576
    width: 1024
    sample_iterations: [7000, 12000, 17000, 22000]
    sample_scales: [0.7, 0.3]
